/** Standalone automatic exam. Private: do not upload to GitHub. */
const EXAM_ID='BOYA2-6-10-AUTO-02';
const KEY={"1": "3", "2": "4", "3": "5", "4": "6", "5": "1", "6": "0", "7": "2", "8": "7", "14": "0", "15": "1", "16": "2", "17": "2", "18": "1", "9": "0", "10": "1", "11": "2", "12": "3", "13": "0", "19": "2", "20": "3", "21": "0", "22": "1", "23": "2", "24": "3"};
const HEADERS=['Thời gian tạo','Mã lượt thi','Mã đề','Họ tên','Lớp','Bắt đầu','Nộp bài','Điền từ /20','Hoàn thành /30','Chọn đáp án /20','Sửa câu /30','Tổng /100','Trạng thái','Nộp trễ','Rời tab','Bài hash','Token hash',...Array.from({length:24},(_,i)=>'Đáp án câu '+(i+1))];
function settings_(){const p=PropertiesService.getScriptProperties();return {sheetId:p.getProperty('SHEET_ID'),origin:p.getProperty('ALLOWED_ORIGIN'),open:p.getProperty('EXAM_OPEN')==='true'};}
function sheet_(){const c=settings_();if(!c.sheetId)throw new Error('Chưa cấu hình SHEET_ID.');const b=SpreadsheetApp.openById(c.sheetId);let s=b.getSheetByName('KetQua_TuDong');if(!s){s=b.insertSheet('KetQua_TuDong');if(s.getMaxColumns()<HEADERS.length)s.insertColumnsAfter(s.getMaxColumns(),HEADERS.length-s.getMaxColumns());s.appendRow(HEADERS);s.setFrozenRows(1);s.getRange(1,1,1,HEADERS.length).setFontWeight('bold').setBackground('#192936').setFontColor('#ffffff');}return s;}
function setup(){sheet_();}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s)).map(b=>(b+256)%256).map(b=>b.toString(16).padStart(2,'0')).join('');}
function safeCell_(s){s=String(s).trim();return /^[=+\-@]/.test(s)?"'"+s:s;}
function findRow_(s,id){if(s.getLastRow()<2)return 0;const x=s.getRange(2,2,s.getLastRow()-1,1).createTextFinder(id).matchEntireCell(true).findNext();return x?x.getRow():0;}
function validate_(p){if(p.examId!==EXAM_ID||!/^a_[a-f0-9]{32}$/.test(p.attemptId)||! /^[a-f0-9]{64}$/.test(p.token))throw new Error('Thông tin lượt thi không hợp lệ.');}
function authenticate_(s,p){const r=findRow_(s,p.attemptId);if(!r||s.getRange(r,17).getValue()!==hash_(p.token))throw new Error('Lượt thi hoặc mã xác nhận sai.');return r;}
function summary_(s,r){const x=s.getRange(r,1,1,HEADERS.length).getValues()[0];return {ok:true,attemptId:x[1],startedAt:new Date(x[5]).getTime(),serverNow:Date.now(),submitted:!!x[6],fill:x[7]===''?null:x[7],completion:x[8]===''?null:x[8],choice:x[9]===''?null:x[9],correction:x[10]===''?null:x[10],total:x[11]===''?null:x[11],status:x[12],late:x[13]===true};}
function start_(s,p){const old=findRow_(s,p.attemptId);if(old){authenticate_(s,p);return summary_(s,old);}if(!settings_().open)throw new Error('Kỳ thi đang đóng.');for(const k of ['name','className'])if(typeof p[k]!=='string'||!p[k].trim()||p[k].length>80)throw new Error('Tên và lớp cần 1–80 ký tự.');const row=Array(HEADERS.length).fill('');row[0]=new Date();row[1]=p.attemptId;row[2]=EXAM_ID;row[3]=safeCell_(p.name);row[4]=safeCell_(p.className);row[5]=new Date();row[12]='Đang thi';row[16]=hash_(p.token);s.appendRow(row);SpreadsheetApp.flush();return summary_(s,s.getLastRow());}
function grade_(answers){const pts=[0,0,0,0];for(let i=1;i<=24;i++){const section=i<=8?0:i<=13?1:i<=18?2:3;const accepted=[KEY[i]];if(i===5)accepted.push('7');if(i===8)accepted.push('1');if(i===16)accepted.push('0');if(accepted.includes(answers[i]))pts[section]+=[2.5,6,4,5][section];}return pts;}
function submit_(s,p){const r=authenticate_(s,p);if(s.getRange(r,7).getValue())return summary_(s,r);if(!p.answers||typeof p.answers!=='object'||Array.isArray(p.answers))throw new Error('Thiếu bài làm.');const a={};for(let i=1;i<=24;i++){const v=p.answers[i];a[i]=typeof v==='string'?v.trim():'';const max=i<=8?7:i<=13||i>=19?3:2;if(a[i]!==''&&(!/^\d$/.test(a[i])||+a[i]>max))throw new Error('Đáp án không hợp lệ.');}const points=grade_(a),x=s.getRange(r,1,1,HEADERS.length).getValues()[0];x[6]=new Date();for(let i=0;i<4;i++)x[7+i]=points[i];x[11]=points.reduce((a,b)=>a+b,0);x[12]='Đã chấm tự động';x[13]=Date.now()-new Date(x[5]).getTime()>32*60000;x[14]=Number.isInteger(p.blurCount)?Math.max(0,Math.min(9999,p.blurCount)):0;x[15]=hash_(JSON.stringify(a));for(let i=1;i<=24;i++)x[16+i]=a[i];s.getRange(r,1,1,HEADERS.length).setValues([x]);SpreadsheetApp.flush();return summary_(s,r);}
function doGet(){return ContentService.createTextOutput('Boya automatic examination service.');}
function doPost(e){let p={},result;try{if(!e.parameter.payload||e.parameter.payload.length>12000)throw new Error('Dữ liệu vượt giới hạn.');p=JSON.parse(e.parameter.payload);if(!/^[a-f0-9]{64}$/.test(p.requestId))throw new Error('Mã yêu cầu sai.');validate_(p);const lock=LockService.getScriptLock();lock.waitLock(20000);try{const s=sheet_();if(p.action==='start')result=start_(s,p);else if(p.action==='submit')result=submit_(s,p);else if(p.action==='status')result=summary_(s,authenticate_(s,p));else throw new Error('Tác vụ không hợp lệ.');}finally{lock.releaseLock();}}catch(err){result={ok:false,error:String(err.message||err).slice(0,180)};}const c=settings_(),origin=/^https:\/\/[A-Za-z0-9.-]+(?::\d+)?$/.test(c.origin||'')?c.origin:'https://invalid.invalid';const message=JSON.stringify({type:'boya-receipt',requestId:p.requestId,result}).replace(/</g,'\\u003c');return HtmlService.createHtmlOutput('<html><body><script>window.top.postMessage('+message+','+JSON.stringify(origin)+');<\/script></body></html>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
