/** Private Apps Script backend. DO NOT publish this file on GitHub Pages. */
const EXAM_ID = 'BOYA2-6-10-01';
const KEY = {"1": "1", "2": "0", "3": "1", "4": "0", "5": "1", "6": "1", "7": "2", "8": "0", "9": "3", "10": "1", "11": "2", "12": "0", "13": "3", "14": "0", "15": "2", "16": "1", "17": "1", "18": "2", "19": "3", "20": "0", "21": "3", "22": "5", "23": "2", "24": "0", "25": "4", "26": "1", "27": "BCA", "28": "BCA", "29": "ACB", "30": "BCA", "31": "1", "32": "2", "33": "3", "34": "2", "35": "0", "36": "1", "37": "3", "38": "1", "39": "2", "40": "0"};
const HEADERS = ['Thời gian tạo','Mã lượt thi','Mã đề','Họ tên','Lớp','Bắt đầu','Nộp bài','Nghe /30','Đọc /40','Viết /30','Tổng /100','Trạng thái','Nộp trễ','Rời tab','Dấu vân tay bài','Token hash','Đáp án trắc nghiệm',...Array.from({length:10},(_,i)=>'Bài viết '+(41+i)),...Array.from({length:10},(_,i)=>'Điểm câu '+(41+i)+' /3')];
function settings_(){const p=PropertiesService.getScriptProperties();return {sheetId:p.getProperty('SHEET_ID'),origin:p.getProperty('ALLOWED_ORIGIN'),open:p.getProperty('EXAM_OPEN')==='true'};}
function book_(){const c=settings_();if(!c.sheetId)throw new Error('Chưa cấu hình SHEET_ID.');return SpreadsheetApp.openById(c.sheetId);}
function sheet_(){const b=book_();let s=b.getSheetByName('KetQua');if(!s){s=b.insertSheet('KetQua');s.appendRow(HEADERS);s.setFrozenRows(1);s.getRange(1,1,1,HEADERS.length).setFontWeight('bold').setBackground('#192936').setFontColor('#ffffff');s.getRange(2,18,Math.max(1,s.getMaxRows()-1),10).setWrap(true);s.getRange(2,28,Math.max(1,s.getMaxRows()-1),10).setDataValidation(SpreadsheetApp.newDataValidation().requireNumberBetween(0,3).setAllowInvalid(false).build());}return s;}
function setup(){sheet_();SpreadsheetApp.getUi().alert('Đã tạo KetQua. Nhập điểm viết tại AB:AK (câu 41–50), 0–3 mỗi câu.');}
function onOpen(){SpreadsheetApp.getUi().createMenu('Boya Chunin').addItem('Tạo bảng kết quả','setup').addItem('Tính lại điểm viết','recalculateAll').addToUi();}
function hash_(x){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(x)).map(b=>(b+256)%256).map(b=>b.toString(16).padStart(2,'0')).join('');}
function safeCell_(s){s=String(s).trim();return /^[=+\-@]/.test(s)?"'"+s:s;}
function findRow_(s,id){if(s.getLastRow()<2)return 0;const m=s.getRange(2,2,s.getLastRow()-1,1).createTextFinder(id).matchEntireCell(true).findNext();return m?m.getRow():0;}
function validate_(p){if(p.examId!==EXAM_ID||!/^a_[a-f0-9]{32}$/.test(p.attemptId)||! /^[a-f0-9]{64}$/.test(p.token))throw new Error('Thông tin lượt thi không hợp lệ.');}
function authenticate_(s,p){const r=findRow_(s,p.attemptId);if(!r||s.getRange(r,16).getValue()!==hash_(p.token))throw new Error('Không tìm thấy lượt thi hoặc mã xác nhận sai.');return r;}
function summary_(s,r){const x=s.getRange(r,1,1,HEADERS.length).getValues()[0];return {ok:true,attemptId:x[1],startedAt:new Date(x[5]).getTime(),serverNow:Date.now(),status:x[11],submitted:!!x[6],listening:x[7]===''?null:x[7],reading:x[8]===''?null:x[8],writing:x[9]===''?null:x[9],total:x[10]===''?null:x[10],late:x[12]===true};}
function start_(s,p){const prior=findRow_(s,p.attemptId);if(prior){authenticate_(s,p);return summary_(s,prior);}if(!settings_().open)throw new Error('Kỳ thi đang đóng. Liên hệ giáo viên.');for(const k of ['name','className']){if(typeof p[k]!=='string'||!p[k].trim()||p[k].length>80)throw new Error('Tên và lớp phải có 1–80 ký tự.');}const row=Array(HEADERS.length).fill('');row[0]=new Date();row[1]=p.attemptId;row[2]=EXAM_ID;row[3]=safeCell_(p.name);row[4]=safeCell_(p.className);row[5]=new Date();row[11]='Đang thi';row[15]=hash_(p.token);s.appendRow(row);SpreadsheetApp.flush();return summary_(s,s.getLastRow());}
function submit_(s,p){const r=authenticate_(s,p);if(s.getRange(r,7).getValue())return summary_(s,r);if(!p.answers||typeof p.answers!=='object'||Array.isArray(p.answers))throw new Error('Thiếu bài làm.');const a={};for(let i=1;i<=50;i++){const v=p.answers[i];a[i]=typeof v==='string'?v.trim():'';if(a[i].length>(i<=40?12:1200))throw new Error('Câu trả lời quá dài.');if(i<=26||i>=31&&i<=40){const max=i<=5?1:i<=20?3:i<=26?5:3;if(a[i]!==''&&(!/^\d$/.test(a[i])||+a[i]>max))throw new Error('Đáp án lựa chọn không hợp lệ.');}else if(i<=30&&a[i]!==''&&!/^[ABC]{3}$/.test(a[i]))throw new Error('Thứ tự câu không hợp lệ.');}
let l=0,d=0;for(let i=1;i<=40;i++)if(a[i]===KEY[i])i<=20?l+=1.5:d+=2;const x=s.getRange(r,1,1,HEADERS.length).getValues()[0];x[6]=new Date();x[7]=l;x[8]=d;x[9]='';x[10]='';x[11]='Chờ chấm viết';x[12]=Date.now()-new Date(x[5]).getTime()>62*60000;x[13]=Number.isInteger(p.blurCount)?Math.max(0,Math.min(9999,p.blurCount)):0;x[14]=hash_(JSON.stringify(a));x[16]=JSON.stringify(Object.fromEntries(Object.entries(a).filter(([k])=>+k<=40)));for(let i=41;i<=50;i++)x[17+i-41]=safeCell_(a[i]);s.getRange(r,1,1,HEADERS.length).setValues([x]);SpreadsheetApp.flush();return summary_(s,r);}
function calculateRow_(s,r){if(r<2||!s.getRange(r,7).getValue())return;const v=s.getRange(r,28,1,10).getValues()[0];const complete=v.every(x=>typeof x==='number'&&Number.isFinite(x)&&x>=0&&x<=3);if(!complete){s.getRange(r,10,1,3).setValues([['','','Chờ chấm viết']]);return;}const writing=v.reduce((a,b)=>a+b,0);const l=+s.getRange(r,8).getValue(),d=+s.getRange(r,9).getValue();s.getRange(r,10,1,3).setValues([[writing,l+d+writing,'Đã chấm']]);}
function onEdit(e){if(!e||e.range.getSheet().getName()!=='KetQua'||e.range.getColumn()>37||e.range.getLastColumn()<28)return;const lock=LockService.getScriptLock();lock.waitLock(20000);try{for(let r=Math.max(2,e.range.getRow());r<=e.range.getLastRow();r++)calculateRow_(e.range.getSheet(),r);}finally{lock.releaseLock();}}
function recalculateAll(){const s=sheet_();const lock=LockService.getScriptLock();lock.waitLock(20000);try{for(let r=2;r<=s.getLastRow();r++)calculateRow_(s,r);}finally{lock.releaseLock();}}
function doGet(){return ContentService.createTextOutput('Boya examination service. Use POST.');}
function doPost(e){let p={};let result;try{if(!e.parameter.payload||e.parameter.payload.length>40000)throw new Error('Dữ liệu vượt giới hạn.');p=JSON.parse(e.parameter.payload);if(!/^[a-f0-9]{64}$/.test(p.requestId))throw new Error('Mã yêu cầu không hợp lệ.');validate_(p);const lock=LockService.getScriptLock();lock.waitLock(20000);try{const s=sheet_();if(p.action==='start')result=start_(s,p);else if(p.action==='submit')result=submit_(s,p);else if(p.action==='status')result=summary_(s,authenticate_(s,p));else throw new Error('Tác vụ không hợp lệ.');}finally{lock.releaseLock();}}catch(err){result={ok:false,error:String(err.message||err).slice(0,180)};}
// Only the configured GitHub origin receives this receipt. No names, answers or secret tokens are returned.
const c=settings_();const origin=/^https:\/\/[A-Za-z0-9.-]+(?::\d+)?$/.test(c.origin||'')?c.origin:'https://invalid.invalid';const message=JSON.stringify({type:'boya-receipt',requestId:p.requestId,result}).replace(/</g,'\\u003c');const html='<html><body><script>window.top.postMessage('+message+','+JSON.stringify(origin)+');<\/script></body></html>';return HtmlService.createHtmlOutput(html).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
